.PHONY:all
all:main1 main2 main3 main4 main5

main1:test_01.c
	gcc $^ -o $@ -g -std=c99
main2:test_02.c
	gcc $^ -o $@ -g -std=c99
main3:test_03.c
	gcc $^ -o $@ -g -std=c99
main4:test_04.c
	gcc $^ -o $@ -g -std=c99
main5:test_05.c
	gcc $^ -o $@ -g -std=c99

clean:
	rm -f main* core.*
