.PHONY:all

all:add.o sub.o mul.o div.o

add.o:add.c 
	gcc -c add.c -o add.o
div.o:div.c
	gcc -c div.c -o div.o
chengfa.o:chengfa.c
	gcc -c mul.c -o mul.o
sub.o:sub.c
	gcc -c sub.c -o sub.o

clean:
	rm -f add.o sub.o chengfa.o div.o
